version: '3.8'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - '80:80'
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - '5000:5000'
    environment:
      - ATLAS_URI=mongodb://mongo:27017/asset-management
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
